services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      args:
        - DEV=${DEV}
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./app:/app
    command: >
      sh -c "python wait_for_db.py && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres_data:
  static_volume:
  media_volume:
